### ISSUE TITLE
你好，怎么编译出来不能播放，提示要登录

### ISSUE THREAD

**Issue by jijinli777** [wxcgeek/lekantv#1]
登录失败，未知错误，注册失败，未知错误。。。网上的后台文件安装了，也是一样，好像没对接的样子哦

**Comment by wxcgeek** [comment]
我是自己使用，所以后台对接那里我随便填写的无法访问的域名。

**Comment by jijinli777** [comment]
是的，找到原因了，写入MariaDB数据库的代码重新搞下可以了，想咨询下，有更改播放器吗，解码是比较重要的问题
